### ISSUE TITLE
Error: Cannot find module 'form-data'

### ISSUE THREAD

**Issue by andrewharvey** [inaturalist/inaturalistjs#35]
When installing inaturalistjs into my node project and running a script which includes it I get `Error: Cannot find module 'form-data'`, installing that module as part of my dependencies fixes the issue.

It's not clear to me why this error occurs since the dependency is in your package.json.

**Comment by kueda** [comment]
Can you post the full stack trace and/or link to your repo if it's online? FWIW, this doesn't sound like it's an issue with inaturalistjs, but maybe we can spot something in your setup.

**Comment by andrewharvey** [comment]
probably something I'm doing wrong, but I really can't tell.

repro at https://gitlab.com/beyondtracks/repro-inaturalistjs-35

steps were,
```
git init
yarn init
yarn add inaturalist/inaturalistjs
```

then create the index.js as per the repro repository and then `./index.js` leads to

```
> ./index.js 
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'form-data'
Require stack:
- /repro-inaturalistjs-35/node_modules/inaturalistjs/lib/inaturalist_api.js
- /repro-inaturalistjs-35/node_modules/inaturalistjs/lib/inaturalistjs.js
- /repro-inaturalistjs-35/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/repro-inaturalistjs-35/node_modules/inaturalistjs/lib/inaturalist_api.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/repro-inaturalistjs-35/node_modules/inaturalistjs/lib/inaturalist_api.js',
    '/repro-inaturalistjs-35/node_modules/inaturalistjs/lib/inaturalistjs.js',
    '/repro-inaturalistjs-35/index.js'
  ]
}

```

**Comment by andrewharvey** [comment]
ah perhaps because form-data is only a devDependency in inaturalistjs not a proper dependency.

**Comment by kueda** [comment]
Thanks, good catch!
